default: &default
  adapter: mysql2
  encoding: utf8
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: release_development
  username: release
  password: release
  url: <%= ENV['DATABASE_URL'] %>

test: &test
  <<: *default
  database: release_test
  username: release
  password: release
  url: <%= ENV["DATABASE_URL"].try(:sub, /([-_]development)?$/, '_test') %>

production:
  <<: *default
  # Rails reads values from DATABASE_URL env var.
