development:
  adapter: mysql2
  encoding: utf8
  database: release_development
  pool: 5
  reconnect: true
  username: release
  password: release

test:
  adapter: mysql2
  encoding: utf8
  database: release_test
  pool: 5
  reconnect: true
  username: release
  password: release
