default: &default
  adapter: mysql2
  encoding: utf8
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: release_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: release_test
  url: <%= ENV["TEST_DATABASE_URL"].try(:sub, /([-_]development)?$/, '_test') %>

production:
  <<: *default
  # Rails reads values from DATABASE_URL env var.
