# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4510401ba61e87ca74871e8938808d943ddbb6f8da27a38e121c386251bbd7a542068cf202499ee05d3eac9e407cd0fd349a6f85e3e8cc83cf2dddb17a4e73a6

test:
  secret_key_base: dff7059ad313a37fe7409d4772d9eea3f54b9d1857d227815bf52c08d4568ffe51ce9998414e4b9241b15091d3f350350b02d8781b0a8d268900adff9fcfe35f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
